fieldLayouts:
  ecc3579d-fd33-4263-8c9a-ae09f137c6c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Drink name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7509c466-8dcc-452f-a77c-ddf44953bb16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd585b1f-baa1-4c7f-ba44-ffdc9ef956f3 # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a50c658c-0ec5-436a-bb12-46d256e27e39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 698c2c75-2a70-480a-852c-8e6c9dc2f095 # Page copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba0bdeaf-4263-470a-8e8b-fdd4569be76b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a683cf6-5953-4f09-8452-49db78a17da1 # Drink image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c19d2b4f-e58b-46ce-a49e-8b3ecba9b26d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 264cb0a3-acc5-4873-a843-2c10221439a1
        userCondition: null
handle: drinks
hasTitleField: true
name: Drinks
section: d067198d-0272-4232-b2b6-778b2c6a7b10 # Drinks
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
