fieldLayouts:
  f116de9a-3dfb-439c-a7fe-2111845202f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: acc06c62-9e69-42fb-a3b4-30cd52caa123
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd585b1f-baa1-4c7f-ba44-ffdc9ef956f3 # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8b09155-302b-4667-8361-62533eecb984
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73f4252e-66e1-47b9-bca6-9539be73126b # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 883380f6-6421-449a-81d8-b2389302478d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 698c2c75-2a70-480a-852c-8e6c9dc2f095 # Page copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 061a4275-cc66-4f22-81f0-8f4605a57398
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5b7235f5-d4d3-4922-92e9-9ee90c0a1203
        userCondition: null
handle: homepage
hasTitleField: false
name: Homepage
section: 18d9a6c5-f2cc-4518-a7d0-0254317ec34c # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
