columnSuffix: fnteyxpg
contentColumnType: text
fieldGroup: d9733ce0-764f-4a3b-87c7-78604d73922c # News
handle: newsBody
instructions: null
name: 'News body'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 0a4d3e62-b383-4317-83ec-0dab9cfcb550 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
