dateModified: 1687987608
email:
  fromEmail: bauerindustries@icloud.com
  fromName: 'crafty coffee'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2e5ac707-b113-48a6-a39f-cd16b37e8dfd: Common # Common
    5d3ef853-3a34-4342-a721-1f59d43ad1b0: 'Public Schema' # Public Schema
    7f9cf7cc-e388-4dd8-819d-17427ec39847: 'Public Schema' # Public Schema
    25dcf5ff-387f-4f58-b014-15685772b51f: 'crafty coffee' # crafty coffee
    684353c1-0d73-43a1-913e-6d34bbadfea9: 'crafty coffee' # crafty coffee
    d39bc870-b3d1-4067-a9ec-dce454eb40d9: 'Public Schema' # Public Schema
system:
  edition: pro
  live: true
  name: 'crafty coffee'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  fieldLayouts:
    a7c8ef5d-8a5f-412b-9da9-f267966e991e: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
